-- サロゲートキーを追加し、主キーとして設定
ALTER TABLE lesson_tags DROP CONSTRAINT lesson_tags_pkey;
ALTER TABLE lesson_tags ADD id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE lesson_tags ADD CONSTRAINT lesson_tags_lesson_id_tag_id_key UNIQUE (lesson_id, tag_id);
