-- 教材で利用する既存タグ
INSERT INTO public.tags (name)
VALUES
    -- 技術・ツール
    ('Java'),
    ('Git'),
    ('GitHub'),
    ('SQL'),
    ('Spring'),
    ('Spring Data JDBC'),
    ('Docker'),
    ('Docker Compose'),
    ('PostgreSQL'),
    ('REST API'),

    -- 学習トピック
    ('オブジェクト指向'),
    ('コレクション'),
    ('Stream API'),
    ('DI'),
    ('バリデーション'),
    ('トランザクション'),
    ('データベース'),
    ('バージョン管理'),
    ('環境構築'),

    -- 難易度・学習段階
    ('入門'),
    ('基礎'),
    ('応用'),
    ('実践')
ON CONFLICT (name) DO NOTHING;
-- 各コースから内容が明確なレッスンを選び、関連するタグを紐づける
-- 一部のレッスンはタグなしとし、必要以上にタグを付与しない
-- レッスンはIDが自動採番のUUIDであるため、コースタイトルとレッスンタイトルで特定する
INSERT INTO public.lesson_tags (lesson_id, tag_id)
SELECT l.id, t.id
FROM (
    VALUES
            ('1章:Java基礎',
             'クラス（概念）',
             ARRAY['Java', 'オブジェクト指向']::VARCHAR[]),
            ('1章:Java基礎',
             '変数と定数',
             ARRAY['Java', '基礎']),
            ('1章:Java基礎',
             'Javaの環境構築（Windowsの方向け）',
             ARRAY['Java', '環境構築']),
            ('1章:Java基礎',
             'クラス（実践）',
             ARRAY['Java', 'オブジェクト指向', '実践']),
            ('1章:Java基礎',
             'Javaの環境構築（Macの方向け）',
             ARRAY['Java', '環境構築']),
            ('1章:Java基礎',
             'カプセル化',
             ARRAY['Java', 'オブジェクト指向']),
            ('1章:Java基礎',
             '条件分岐',
             ARRAY['Java', '基礎']),
            ('1章:Java基礎',
             'Javaプログラムの基本構造',
             ARRAY['Java', '入門']),
            ('1章:Java基礎',
             'デバッグ',
             ARRAY['Java', '実践']),
            ('1章:Java基礎',
             '繰り返し処理',
             ARRAY['Java', '基礎']),
            ('2章:Git',
             'GitHubにpushしてPull Requestを作ろう',
             ARRAY['GitHub', '実践']),
            ('2章:Git',
             'git initで自分のリポジトリを作ろう',
             ARRAY['Git', '基礎']),
            ('2章:Git',
             'GitとGitHubとは何か',
             ARRAY['Git', 'GitHub', 'バージョン管理', '入門']),
            ('2章:Git',
             'git fetchとgit pullでチームの変更を取り込もう',
             ARRAY['Git', 'GitHub']),
            ('2章:Git',
             'Gitの環境構築とSSH設定',
             ARRAY['Git', '環境構築']),
            ('2章:Git',
             'コンフリクトを解消しよう',
             ARRAY['Git', '実践']),
            ('2章:Git',
             'ファイルを修正してステージング・コミットしよう',
             ARRAY['Git', 'バージョン管理']),
            ('2章:Git',
             'ブランチとHEADを理解しよう',
             ARRAY['Git', 'バージョン管理']),
            ('3章:Java応用',
             'Java実践課題：じゃんけんゲームを作ろう',
             ARRAY['Java', '実践']),
            ('3章:Java応用',
             '関数型インターフェース、ラムダ式、メソッド参照',
             ARRAY['Java', '応用']),
            ('3章:Java応用',
             'StreamAPI',
             ARRAY['Java', 'Stream API']),
            ('3章:Java応用',
             'Optional',
             ARRAY['Java', '応用']),
            ('3章:Java応用',
             '継承',
             ARRAY['Java', 'オブジェクト指向', '応用']),
            ('3章:Java応用',
             'インターフェースと実装',
             ARRAY['Java', 'オブジェクト指向', '応用']),
            ('3章:Java応用',
             'ポリモーフィズム',
             ARRAY['Java', 'オブジェクト指向', '応用']),
            ('3章:Java応用',
             'コレクションフレームワーク（List, Map, Set）',
             ARRAY['Java', 'コレクション']),
            ('3章:Java応用',
             '例外処理',
             ARRAY['Java', '応用']),
            ('4章:SQL',
             'データベースとSQLとは？',
             ARRAY['SQL', 'データベース', '入門']),
            ('4章:SQL',
             'データを取り出してみよう（SELECT）',
             ARRAY['SQL', '基礎']),
            ('4章:SQL',
             'データを安全に更新しよう（トランザクション）',
             ARRAY['SQL', 'トランザクション']),
            ('4章:SQL',
             'データを追加・更新・削除しよう（INSERT・UPDATE・DELETE）',
             ARRAY['SQL', 'データベース']),
            ('4章:SQL',
             'データを集計しよう（GROUP BY・HAVING）',
             ARRAY['SQL', '応用']),
            ('4章:SQL',
             'テーブルを設計しよう（DDL・制約）',
             ARRAY['SQL', 'データベース']),
            ('4章:SQL',
             '複数テーブルを結合しよう（JOIN）',
             ARRAY['SQL', '応用']),
            ('4章:SQL',
             '実務で使える便利機能（インデックス・ビュー）',
             ARRAY['SQL', '実践']),
            ('5章:Spring',
             'DIについて理解しよう（Beanの生成）',
             ARRAY['Spring', 'DI']),
            ('5章:Spring',
             'FlywayでDB（PostgreSQL）に初期テーブル・初期データを作成しよう',
             ARRAY['Spring Data JDBC', 'PostgreSQL', 'データベース']),
            ('5章:Spring',
             'Springの概要',
             ARRAY['Spring', '入門']),
            ('5章:Spring',
             '@Transactionalについて理解しよう',
             ARRAY['Spring', 'トランザクション']),
            ('5章:Spring',
             'ユーザーとその趣味という1対多を実装しよう',
             ARRAY['Spring', 'Spring Data JDBC', 'データベース']),
            ('5章:Spring',
             'リクエストを検証し、400を返そう',
             ARRAY['Spring', 'バリデーション']),
            ('5章:Spring',
             'DIについて理解しよう（Beanの注入）',
             ARRAY['Spring', 'DI']),
            ('5章:Spring',
             'Spring Bootのプロジェクトを作成しよう',
             ARRAY['Spring', '環境構築']),
            ('5章:Spring',
             'ユーザー一覧取得APIを実装しよう',
             ARRAY['Spring', 'REST API']),
            ('5章:Spring',
             '同時リクエストされても大丈夫なように、ロックを実装しよう',
             ARRAY['Spring', 'トランザクション', '実践']),
            ('5章:Spring',
             '派生クエリメソッドでユーザー一覧取得APIを改善しよう',
             ARRAY['Spring Data JDBC', 'REST API']),
            ('5章:Spring',
             '@Queryでユーザー検索APIを作ろう',
             ARRAY['Spring Data JDBC', 'REST API']),
            ('5章:Spring',
             'REST APIとJSONを理解しよう',
             ARRAY['Spring', 'REST API']),
            ('5章:Spring',
             'Postmanで最初のAPIを動かしてみよう',
             ARRAY['Spring', 'REST API', '実践']),
            ('6章:Docker',
             'Docker Hubとイメージ',
             ARRAY['Docker', '基礎']),
            ('6章:Docker',
             'dockerコマンドの基本と、コンテナのライフサイクル',
             ARRAY['Docker', '基礎']),
            ('6章:Docker',
             'Dockerとは？',
             ARRAY['Docker', '入門']),
            ('6章:Docker',
             'Webサーバを立ち上げてみよう【ポートフォワーディング】',
             ARRAY['Docker', '実践']),
            ('6章:Docker',
             'コンテナを消してもデータを守る方法1【バインドマウント】',
             ARRAY['Docker', '実践']),
            ('6章:Docker',
             'コンテナ間で通信できるようにする【ネットワーク】',
             ARRAY['Docker', '応用']),
            ('6章:Docker',
             '総合課題：タスク管理APIを作成しよう',
             ARRAY['Docker', 'Docker Compose', 'REST API', '実践']),
            ('6章:Docker',
             '複数コンテナを一発起動する【Docker Compose】',
             ARRAY['Docker', 'Docker Compose']),
            ('6章:Docker',
             'Dockerの環境構築とHelloWorld',
             ARRAY['Docker', '環境構築']),
            ('6章:Docker',
             '設定ファイルからイメージを作る方法【Dockerfile】',
             ARRAY['Docker', '実践'])
) AS seed(course_title, lesson_title, tag_names)
JOIN public.courses c
  ON c.title = seed.course_title
JOIN public.lessons l
  ON l.title = seed.lesson_title
 AND l.course_id = c.id
CROSS JOIN LATERAL UNNEST(seed.tag_names) AS seeded_tag(name)
JOIN public.tags t ON t.name = seeded_tag.name
ON CONFLICT (lesson_id, tag_id) DO NOTHING;
