-- タグ
CREATE TABLE tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- タグID
    name VARCHAR(255) NOT NULL UNIQUE,      -- タグ名（ユニーク）
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  -- 更新日時
);

-- 中間テーブル：レッスンに紐づくタグ
CREATE TABLE lesson_tags (
    lesson_id INTEGER REFERENCES lessons(id) ON DELETE CASCADE, -- レッスンID
    tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE, -- タグID
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
    PRIMARY KEY (lesson_id, tag_id)                    -- 複合主キー
);